name: Bug report
description: Submit a bug report
labels: ["type-bug"]
body:
  - type: textarea
    attributes:
      label: "Bug description:"
      description: >
        Give a clear and concise description of what happened.
        Include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if possible.
        [Copy and paste code where possible rather than using screenshots](https://meta.stackoverflow.com/a/285557/13990016),
        and put any code blocks inside triple backticks.

      value: |
        ```python
        # Add a code block here, if required
        ```
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Operating systems tested on:"
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: false
