# runs python scripts/pack.py to create a desktop build
# the build is at packaging/dist/latest/xxx.zip
# the build is uploaded to s3 with shallwefootball/s3-upload-action@master

name: Standalone CD
# only run on tag push
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout with submodules
      - name: Get token from Github App
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PEM }}
          # owner is required, otherwise the creds will fail the checkout step
          owner: ${{ github.repository_owner }}
      
      - name: Checkout from GitHub
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ steps.app_token.outputs.token }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r packaging/pack_requirements.txt
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: |
          cd frontend && npm install && cd ..
          cd submodules/topicsync-client && npm install && cd ../..
          cd submodules/objectsync-client && npm install && cd ../..
        
      - name: Decode pyarmor registration file
        env: 
          REGFILE: ${{ secrets.PYARMOR_REGFILE }}
        run: |
          echo $REGFILE | base64 -d > ~/.pyarmor-regfile-4553.zip
      - name: Register pyarmor
        run: |
          pyarmor reg ~/.pyarmor-regfile-4553.zip && rm ~/.pyarmor-regfile-4553.zip
      - name: Run pack.py with --name 6 digits of commit hash
        run: python scripts/pack.py --platform linux.x86_64 --name $(echo $GITHUB_SHA | cut -c1-6) --folder_name build
      - name: Upload artifact for testing
        uses: actions/upload-artifact@v2
        with:
          name: standalone
          path: packaging/dist/build/*.zip

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: standalone
          path: packaging/dist/build
      - name: Unzip artifact
        run: unzip packaging/dist/build/*.zip -d packaging/dist/build/grapycal
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install and run grapycal
        run: |
          cd packaging/dist/build/grapycal
          python install.py
          python main.py &
      - name: Wait for 20 seconds
        run: sleep 20
      - name: Check if Grapycal is running
        run: ps aux | grep main.py | grep -v grep || exit 1
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: standalone
          path: packaging/dist/build
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp packaging/dist/build/*.zip s3://${{ secrets.S3_DESKTOP_ARTIFACT_BUCKET }}/releases/
